management:
  security:
    enabled: false
spring:
  redis:
    host: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000
