
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
  zipkin:
    locator:
      discovery:
        enabled: false
zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: mysql
